version: 2

updates:
  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "${{ github.repository_owner }}"
    labels:
      - "dependencies"
      - "backend"
      - "automated"
    commit-message:
      prefix: "build(backend)"
      include: "scope"
    versioning-strategy: increase
    groups:
      # Group all patch updates together
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      # Group type definitions together
      types:
        patterns:
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
      # Group testing dependencies
      testing:
        patterns:
          - "jest*"
          - "@types/jest"
          - "ts-jest"
        update-types:
          - "minor"
          - "patch"

  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "${{ github.repository_owner }}"
    labels:
      - "dependencies"
      - "frontend"
      - "automated"
    commit-message:
      prefix: "build(frontend)"
      include: "scope"
    versioning-strategy: increase
    groups:
      # Group all patch updates together
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
      # Group type definitions together
      types:
        patterns:
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
      # Group React ecosystem
      react:
        patterns:
          - "react*"
          - "@types/react*"
        update-types:
          - "minor"
          - "patch"
      # Group testing dependencies
      testing:
        patterns:
          - "jest*"
          - "@testing-library/*"
          - "@types/jest"
        update-types:
          - "minor"
          - "patch"
      # Group build tools
      build-tools:
        patterns:
          - "vite"
          - "@vitejs/*"
          - "typescript"
          - "eslint*"
          - "@typescript-eslint/*"
        update-types:
          - "minor"
          - "patch"

  # Root dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "root"
      - "automated"
    commit-message:
      prefix: "build(root)"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      # Group all GitHub Actions updates
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "docker"
      - "automated"
    commit-message:
      prefix: "build(docker)"

