# Security-focused Docker Compose override
# Use with: docker-compose -f docker-compose.yml -f docker-compose.security.yml up

version: '3.8'

services:
  werewolf-game:
    # Add security-specific configuration
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /app/backend/logs
    environment:
      - NODE_ENV=production
      - PORT=3001
      # Enable security headers
      - SECURITY_HEADERS=true
      # Disable unnecessary features
      - NODE_OPTIONS=--no-deprecation
    # Resource limits to prevent DoS
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # Health check with tighter timeouts
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (r) => process.exit(r.statusCode === 200 ? 0 : 1))"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s

  # Security scanner service (optional, for development)
  security-scanner:
    image: snyk/snyk:alpine
    volumes:
      - .:/app:ro
    working_dir: /app
    environment:
      - SNYK_TOKEN=${SNYK_TOKEN}
    command: >
      sh -c "
        echo '🔒 Running security scan...' &&
        snyk test --severity-threshold=medium backend/ || true &&
        snyk test --severity-threshold=medium frontend/ || true &&
        echo '✅ Security scan completed'
      "
    profiles:
      - security-scan
      
  # Trivy security scanner (alternative)
  trivy-scanner:
    image: aquasec/trivy:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - .:/workspace:ro
    working_dir: /workspace
    command: >
      sh -c "
        echo '🔍 Running Trivy security scan...' &&
        trivy fs --severity HIGH,CRITICAL . &&
        echo '✅ Trivy scan completed'
      "
    profiles:
      - security-scan

